name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    # Navigate to the Android app directory
    - name: Change to Android App directory
      run: cd OOPs-I-Pushed-To-Main-CIAgain/src/OOPsIPushedToMain/

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: cd src/OOPsIPushedToMain/ && ./gradlew runSpecificTest -PtestClass=com.oopsipushedtomain.FirebaseAccessUnitTest

